CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS creation_db;
CREATE DATABASE IF NOT EXISTS gameplay_db;
CREATE DATABASE IF NOT EXISTS knowledge_db;
CREATE DATABASE IF NOT EXISTS toolchain_db;
CREATE DATABASE IF NOT EXISTS progression_db;
CREATE DATABASE IF NOT EXISTS feedback_db;
