export enum TagCategory {
  GAME_TYPE = 'game_type',         // 游戏类型：本格/新本格/变格
  AGE_GROUP = 'age_group',         // 年龄段
  PLAYER_COUNT = 'player_count',   // 玩家人数
  ERA = 'era',                     // 时代背景
  THEME = 'theme',                 // 主题风格
  CUSTOM = 'custom',               // 用户自定义
}

export interface Tag {
  id: string;
  name: string;
  category: TagCategory;
}

export interface ScriptTag {
  scriptId: string;
  tagId: string;
  isAutoGenerated: boolean;    // 系统自动生成 vs 用户手动添加
}
